apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-capstone-al
  region: {{REGION}}
  version: "1.32"

kubernetesNetworkConfig: 
  serviceIPv4CIDR: 10.100.0.0/16

availabilityZones: ["{{REGION}}a", "{{REGION}}b"]
    
iam:
  withOIDC: true

  serviceAccounts:
  - metadata:
      name: cluster-autoscaler-al
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: aws-lb-controller-al
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
  - name: amazon-cloudwatch-observability
    version: latest
 
managedNodeGroups:
  - name: nodegroup-al-1
    instanceType: t3.medium
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    volumeEncrypted: true
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true
        autoScaler: true
        ebs: true
        xRay: true
 
fargateProfiles:
  - name: on-fargate
    selectors:
      - namespace: on-fargate
  - name: myprofile
    selectors: 
    - namespace: prod
      labels: 
       stack: frontend

cloudWatch:
    clusterLogging:
        enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]