apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: angular
 name: angular-{{DEPLOYMENT_COLOR}}
spec:
 replicas: 3
 selector:
   matchLabels:
     app: angular
     color: {{DEPLOYMENT_COLOR}}
     ver: {{VERSION_TAG}}
 template:
   metadata:
     labels:
       app: angular
       color: {{DEPLOYMENT_COLOR}}
       ver: {{VERSION_TAG}}
   spec:
     containers:
     - image: {{AWS_ACCOUNT_ID}}.dkr.ecr.{{REGION}}.amazonaws.com/capstone-al-angular:{{VERSION_TAG}}
       name: angular
       resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
       ports:
       - containerPort: 80